name: CI Pipeline

on:
    push:
        branches:
            main
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout code
            uses: actions/checkout@v2 # Checkout the repository code

        -   name: Set up Node.js
            uses: actions/setup-node@v2 # Set up the Node.js environment
            with:
                node-version: '14' # Specify the Node.js version to use

        -   name: Install dependencies
            run: npm install # Install project dependencies defined in package.json

        -   name: Run tests
            run: npm test # Execute the test script defined in package.json

        -   name: Deploy
            run: npm run deploy # Execute the deployment script
        